import { appName } from '../brand'

export const texts = {
  appTitle: 'Home',
  headerBrand: appName,
  selectCertification: 'Choose your certification',
  emptyStateBefore: 'No certification bundles loaded. Valid bundles placed in',
  emptyStateHighlight: 'src/assets/',
  emptyStateAfter: 'are discovered automatically at build time.',
  questionBankLabel: 'Question bank',
  realExamLabel: 'Real exam',
  realExamValue: (count: number) => `${count} question${count === 1 ? '' : 's'}`,
  timeLimitLabel: 'Time limit',
  timeLimitValue: (minutes: number) => `${minutes} minute${minutes === 1 ? '' : 's'}`,
  passingScoreLabel: 'Passing score',
  startQuizCta: 'New quiz →',
  viewDashboardCta: 'View dashboard →',
  requestNoticeBefore: 'A bug? An issue with a question? Missing a certification?',
  requestNoticeLink: 'open a GitHub issue',
  modeLabel: 'Mode',
  modePreparation: 'Prep',
  modePreparationDescription: 'Optional timer. Can click "Submit answer" to reveal the answer.',
  modeExam: 'Exam',
  modeExamDescription: 'Real exam conditions: fixed settings, answers revealed once the quiz is over.',
  examSettingsLabel: 'Real exam settings',
  examReplayUnavailable: (needed: number, available: number) => `needs ${needed}, but ${available} available`,
  examReadyValue: (count: number) => `${count} question${count === 1 ? '' : 's'}, sampled at random`,
  examPoolTooSmallWarning: 'Not enough questions to build a full exam.',
  replayLabel: 'Replay mode',
  replayAll: 'All questions',
  replayWrong: 'I got wrong',
  replayFlagged: 'Flagged',
  replayUnattempted: 'Unattempted',
  timerLabel: 'Timer',
  timerEnable: 'Time this quiz',
  timerMinutesLabel: 'Duration in minutes',
  timerMinutesUnit: 'minutes',
  countLabel: 'Number of questions',
  countAll: (n: number) => `All matching (${n})`,
  countCustomLabel: 'Custom count',
  includeLabel: 'Include themes',
  excludeLabel: 'Exclude themes',
  topicsLabel: 'Topics',
  topicsAllOption: 'All',
  matchTagsLabel: 'Match tags',
  matchGroupsLabel: 'Match groups',
  quickSetupLabel: 'Quick setup',
  filterQuestionsLabel: 'Filter questions',
  matchAny: 'Match any',
  matchAll: 'Match all',
  matchAnyGroups: 'Match any group',
  matchAllGroups: 'Match all groups',
  matchingCountValue: (n: number) => `${n} question${n === 1 ? '' : 's'} match your filters`,
  noMatchWarning: 'No question matches your filters — widen them.',
  themeToggle: (dark: boolean) => (dark ? 'Switch to light mode' : 'Switch to dark mode'),
  questionOf: (n: number, total: number) => `Question ${n} of ${total}`,
  previous: 'Previous',
  next: 'Next',
  finish: 'Finish quiz',
  flag: 'Flag for review',
  unflag: 'Remove flag',
  flagged: 'Flagged',
  promptImageAlt: 'Prompt image',
  correct: 'Correct',
  incorrect: 'Incorrect',
  explanation: 'Explanation',
  topic: 'Topic',
  yourAnswer: 'Your answer',
  correctAnswer: 'Correct answer',
  noAnswer: 'No answer selected',
  timeUp: 'Time is up',
  submit: 'Submit answer',
  reviewTitle: 'Quiz review',
  passed: 'Passed',
  failed: 'Did not pass',
  correctCount: (n: number, total: number) => `${n} of ${total} correct`,
  projectedScaledScore: (score: number, scale: number) => `Projected scaled score: ${score} / ${scale}`,
  scaledScoreDisclaimer: 'This projected score is a linear projection and does not reflect the official certification scoring algorithm.',
  scoreBreakdownByTopic: 'Score by topic',
  scoreBreakdownByTheme: 'Score by theme',
  selectQuestionHint: 'Select a question to review its details.',
  themeGroupDisplay: (groupLabel: string, values: string[]) => `${groupLabel}: ${values.join(', ')}`,
  toCertsList: '← Certifications list',
  quizzesTaken: 'Quizzes taken',
  overallAccuracy: 'Overall accuracy',
  correctAnswers: 'Correct answers',
  quizHistory: 'Quiz history',
  noQuizzesTaken: 'No quizzes taken yet.',
  completedIn: (duration: string) => `Completed in ${duration}`,
  review: 'Review',
  reviewFlagged: 'Review flagged questions only',
  delete: 'Delete',
  deleteQuizTitle: 'Delete quiz',
  deleteQuizMessage: 'Are you sure you want to delete this quiz from your history?',
  resetAllTitle: 'Reset all progress',
  resetAllMessage: 'This will delete all quiz history and reset per-question progress for this certification. This cannot be undone.',
  resetAll: 'Reset all',
  cancel: 'Cancel',
  quizNotFoundTitle: 'Quiz not found',
  quizNotFoundMessage: 'This quiz is no longer in your history. It may have been deleted or reset.',
  noQuestionsFoundMessage: 'No questions found for this topic or theme.',
  topicReviewTitle: (topic: string) => `Topic: ${topic}`,
  themeReviewTitle: (theme: string, value: string) => `${theme}: ${value}`,
  flaggedReviewTitle: 'Flagged questions',
  questionsForTopic: (topic: string) => `Questions for topic "${topic}"`,
  questionsForTheme: (value: string) => `Questions for theme "${value}"`,
  flaggedQuestions: 'Questions you have flagged for review',
  goBackToDashboard: '← To dashboard',
  questionBankValue: (n: number) => `${n} questions`,
  questionBankTotal: (n: number) => `${n.toLocaleString('en-US')} questions`,
  examsIncluded: (n: number) => `${n} certifications available`,
  welcomeEyebrowPoints: ['100% free', 'No account required', 'Tailor quizzes to the topics you need to practice'],
  welcomeIntroTitle: 'Practice for certification exams',
  welcomeHowItWorksTitle: 'How it works',
  welcomeNoAccount: 'Start practicing now',
  welcomeNoAccountDesc:
    'No account needed. Progress stays in this browser — sign in later to sync it everywhere.',
  welcomeNoAccountDescNoSync:
    'No account needed. Progress stays in this browser only — clearing site data or using private browsing erases it.',
  welcomeNoAccountCta: 'Choose your certification →',
  welcomeNewAccountCta: 'Create an account →',
  welcomeExistingAccountCta: 'Sign in →',
  welcomeSyncTitle: 'Want your progress on every device?',
  welcomeSyncDesc: 'Create a free account, or sign in to an existing one, to sync your progress across devices.',
  welcomeSyncDescNoSync: 'Sync is not enabled yet, but you can still create an account on this device.',
  welcomeUploadData: 'Upload my local data',
  welcomeUploadDataDesc: 'This browser has saved progress. Sign in to merge it into your account and sync it everywhere.',
  welcomeUploadDataCta: 'Upload my data →',
  authSignInTitle: 'Sign in',
  authSignUpTitle: 'Create an account',
  authEmailLabel: 'Email',
  authPasswordLabel: 'Password',
  authSignInCta: 'Sign in →',
  authSignUpCta: 'Create account →',
  authConfirmTitle: 'Check your inbox',
  authConfirmHint: 'We sent a verification code to your email address. Enter it below to activate your account.',
  authConfirmCodeLabel: 'Verification code',
  authConfirmCta: 'Verify and continue →',
  authSwitchToSignUp: 'No account yet? Create one',
  authSwitchToSignIn: 'Already have an account? Sign in',
  authUploadHint: 'The progress saved in this browser will be merged into the account you sign in with.',
  authSwitchToReset: 'Forgot your password?',
  authSwitchToConfirm: 'Never confirmed your account? Send a new code',
  authResetTitle: 'Reset your password',
  authResetHint: 'Enter your account email address and we will send you a reset code.',
  authResetCta: 'Send reset code →',
  authResetRequestError: 'Could not send the reset code. Check the email address and try again.',
  authResetConfirmTitle: 'Enter your reset code',
  authResetConfirmHint: 'We sent a reset code to your email address. Enter it below together with your new password.',
  authNewPasswordLabel: 'New password',
  authResetConfirmCta: 'Set new password and sign in →',
  authResetConfirmError: 'Password reset failed. Check the code and your new password, then try again.',
  authResetCompleted: 'Your password has been reset. Sign in with your new password.',
  authResendCode: "Didn't get the code? Send it again",
  authCodeResent: 'A new code was sent to your email address.',
  authResendError: 'Could not resend the code. Try again in a moment.',
  authSignInError: 'Sign-in failed. Check your email and password, then try again.',
  authUnconfirmedNotice: 'Your account still needs to be verified. Enter the code we emailed you.',
  signIn: 'Sign in',
  authSignUpError: 'Account creation failed. Check your details and try again.',
  authWeakPasswordError: 'Password must be at least 6 characters.',
  authConfirmError: 'Verification failed. Check the code and try again.',
  authConfirmCompleted: 'Your account is verified. Sign in with your password.',
  signOut: 'Sign out',
  notFoundTitle: 'Page not found',
  notFoundDescription:
    'This page does not exist. The link may be broken, or the address may have a typo.',
  notFoundPathLabel: 'Requested path',
  notFoundHomeCta: '← Back to home',
  notFoundCertsCta: 'Browse certifications →',
  syncFailed: 'Synchronization failed. Your local data is safe; try again later.',
  dismiss: 'Dismiss',
}
